// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgtqcxutihnojcebjfjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ndHFjeHV0aWhub2pjZWJqZmpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjAwMjEsImV4cCI6MjA3MjEzNjAyMX0.KIGkx3ffdde5jAwwInU2pbtD24Edt9K7KOetKTNGlZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});